name: CI

on:
  push:
    branches:
      - bt1

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker info

      - name: Build application
        working-directory: ./user-service
        run: ./gradlew bootJar

      - name: Build Docker image
        run: docker build -t quickbite-test ./user-service